### ISSUE TITLE
Hogere DPI instelling kan diagrammen afkappen

### ISSUE THREAD

**Issue by DevNebulae** [luudvkeulen/PlantUMLISStijl#2]
Als `dpi 300` gebruikt wordt kan het wel eens zijn dat bij de wat grotere klassediagrammen maar de helft goed uit de render komt. Zie voorbeeld.

![kappa](https://user-images.githubusercontent.com/12952123/48765506-90a70980-ecb2-11e8-8000-70f2946989a8.png)

Dit hoort het normaal te zijn.

![kappa](https://user-images.githubusercontent.com/12952123/48765569-b0d6c880-ecb2-11e8-8664-c8550c74b0a8.png)

**Comment by bvkeersop** [comment]
Man man man, Luud en Ids zijn echt een stel stumpers....
